apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-test
  namespace: vault
  labels:
    app: read-vault-secret
spec:
  selector:
    matchLabels:
      app: read-vault-secret
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-clisecret: "secret/clisecret"
        vault.hashicorp.com/agent-inject-template-clisecret: |
          {{- with secret "secret/clisecret" -}}
          pattoken={{ .Data.data.token }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-uisecret: "secret/uisecret"
        vault.hashicorp.com/agent-inject-template-uisecret: |
          {{- with secret "secret/uisecret" -}}
          username={{ .Data.data.username }}
          password={{ .Data.data.password }}
          {{- end }}
        vault.hashicorp.com/role: "vault-role"
      labels:
        app: read-vault-secret
    spec:
      serviceAccountName: vault-serviceaccount
      containers:
      - name: nginx
        image: nginx
